# Generated by Django 5.0.1 on 2025-05-03 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioEscolar',
            fields=[
                ('id_ano', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del año')),
                ('nombreano', models.CharField(max_length=9, verbose_name=' Nombre*')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Año Escolar',
                'verbose_name_plural': 'Años Escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Cargo')),
                ('nombre_cargo', models.CharField(max_length=50, unique=True, verbose_name='Especialidad *')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre_cargo'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Estudiante')),
                ('tipo_cedula_estudiante', models.CharField(max_length=2)),
                ('cedula_estudiante', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Cédula *')),
                ('nombre_estudiante', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombres *')),
                ('apellido_estudiante', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellidos * ')),
                ('telefono_estudiante', models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono')),
                ('correo_estudiante', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['cedula_estudiante'],
            },
        ),
        migrations.CreateModel(
            name='Intere',
            fields=[
                ('id_g', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Grupo ')),
                ('nombre_grupo', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre del Grupo *')),
                ('descripcion_grupo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion del Grupo')),
                ('contador_estudiantes', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Estudiantes')),
                ('status', models.CharField(max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Intere',
                'verbose_name_plural': 'Interes',
                'ordering': ['nombre_grupo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico ')),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
                ('cuenta_bloqueada', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Inscripción')),
                ('seccion', models.CharField(max_length=20)),
                ('ano_curso', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Año Cursante *')),
                ('tipo_cedula_estudiante', models.CharField(max_length=2)),
                ('cedula_estudiante', models.CharField(max_length=20, verbose_name='Cédula del Estudiante *')),
                ('nombre_estudiante', models.CharField(max_length=100, verbose_name='Nombres del Estudiante *')),
                ('apellido_estudiante', models.CharField(max_length=100, verbose_name='Apellidos del Estudiante *')),
                ('nombre_grupo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombreano', models.TextField(verbose_name='Nombre')),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.anioescolar', verbose_name='Año Escolar')),
                ('id_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Project.estudiante', verbose_name='Estudiante')),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.intere', verbose_name='grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuentro_numero', models.IntegerField()),
                ('asistio', models.BooleanField(default=False)),
                ('fecha_encuentro', models.DateField(blank=True, null=True)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.inscripcion')),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.intere')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte_1', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('corte_2', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('corte_3', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.inscripcion', verbose_name='Inscripción')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id_pla', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Planificacion')),
                ('nombre_pla', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre de la Planificacion *')),
                ('fecha_inicio', models.DateField(verbose_name='Por Favor Ingrese Fecha de Inicio de la planificacion *')),
                ('fecha_final', models.DateField(verbose_name='Por Favor Ingrese Fecha de Final de la planificacion *')),
                ('observacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Observacion de la planificación')),
                ('nombre_grupo', models.TextField(verbose_name='Nombre')),
                ('limite_actividades', models.PositiveIntegerField(default=1, verbose_name='Límite de Actividades')),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.intere', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_act', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Actividad')),
                ('nombre_actividad', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre del Actividad *')),
                ('descripcion_actividad', models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion de la Actividad')),
                ('fecha_Actividad', models.DateField(verbose_name='Por Favor Ingrese Fecha de la Actividad')),
                ('nombre_pla', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_grupo', models.TextField(verbose_name='Nombre')),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.intere', verbose_name='Grupo')),
                ('id_pla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.planificacion', verbose_name='Planificación')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha_Actividad'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Profesor')),
                ('tipo_cedula_profesor', models.CharField(max_length=2)),
                ('cedula_profesor', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Cedula del Profesor *')),
                ('nombre_profesor', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre del Profesor *')),
                ('apellido_profesor', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellido del Profesor * ')),
                ('telefono_Profesor', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Telefono del Profesor ')),
                ('nombre_cargo', models.TextField(verbose_name='Cargo del Trabajador *')),
                ('fecha_ingreso', models.DateField(verbose_name='Por Favor Ingrese Fecha de Ingreso del Profesor *')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.cargo', verbose_name='Cargo *')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['cedula_profesor'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_h', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Horario')),
                ('semana_grupo', models.CharField(max_length=12)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('nombre_grupo', models.TextField(verbose_name='Nombre')),
                ('tipo_cedula_profesor', models.CharField(max_length=2)),
                ('cedula_profesor', models.TextField(verbose_name='Cedula del Profesor')),
                ('nombre_profesor', models.TextField(verbose_name='Nombre del Profesor')),
                ('apellido_profesor', models.TextField(verbose_name='Apellido del Profesor')),
                ('nombreano', models.TextField(verbose_name='Nombre')),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.anioescolar', verbose_name='Año Escolar')),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.intere', verbose_name='Grupo de Interes * ')),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.profesor', verbose_name='Profesor Asignado * ')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['semana_grupo'],
            },
        ),
    ]
